Docs: Refactor documentation
Orange-OpenSource/ods-android pull request #808
Opened 2024-02-06 17:37 UTC by louismaximepiton

### Description

* Update CONTRIBUTING.md to better fit to the project structure
* Refactoring of the main page, removing some CSS as well
* Adding the Orange font inside the doc ⚠️ Should be done on `ods-jekyll-theme` side?
* Introducing some partials for header and footer for clearer template

2024-02-16 13:07 UTC, paulinea approved these changes

2024-02-20 12:55 UTC, julien-deramond requested changes
I haven't finished the review for the HTML part, but here are some first comments.

2024-02-20 12:55 UTC, julien-deramond commented on docs/_includes/header.html
> +          <img src="https://c.woopic.com/logo-orange.png" width="50" height="50" alt="ODS Android" loading="lazy">
I think this is not the right icon, it should be the SVG version which contains the minified version at some breakpoints. Given the fact that there won't be too many users related to this documentation, you could try to use this one https://boosted.orange.com/docs/5.3/assets/brand/orange-logo.svg.
I know it's linked to a fixed 5.3 version, but this image is not in the Woopic CDN for now.

2024-02-20 14:34 UTC, julien-deramond approved these changes
LGTM. Some enhancements could be made to the HTML part but let's do them step-by-step in the future. This version is already a great improvement for the users 🚀 
Thanks for the PR @louismaximepiton

2024-02-21 16:34 UTC, louismaximepiton commented on docs/modules/About_docs.md
> +title: About
Good catch, it should be resolved by https://github.com/Orange-OpenSource/ods-android/pull/808/commits/a33440625ef3645e34870fed2b8e9e53682348d2

2024-02-22 09:44 UTC, florentmaitre approved these changes

2024-02-22 10:35 UTC, merged