Refactor spacings and typography
Orange-OpenSource/ods-android pull request #922
Opened 2024-05-02 13:49 UTC by florentmaitre

2024-05-17 13:45 UTC, paulinea requested changes

2024-05-17 13:45 UTC, paulinea commented on theme-contract/src/main/java/com/orange/ods/theme/spacing/OdsSpacings.kt
> +interface OdsSpacingsCatalog<T> : OdsThemeConfigurationItem.Catalog<T> {
Here we have something generic but can we have something else than an `OdsSpacingCatalog` of `OdsSpacing`?

2024-05-17 13:45 UTC, paulinea commented on app/src/main/java/com/orange/ods/app/ui/components/chips/Chip.kt
> +                        modifier = Modifier.padding(horizontal = OdsTheme.spacings.medium.dp),
There is always a reference to `com.orange.ods.R.dimen.spacing_m` in `Chips.md` line 205

2024-05-17 13:45 UTC, paulinea commented on theme-contract/src/main/java/com/orange/ods/theme/spacing/OdsSpacing.kt
> +            get() = dimensionResource(id = id)
As discussed together, we can remove `dimens` and simplify usage of spacings and remove `.dp` to access spacing value.

2024-05-17 13:45 UTC, paulinea commented on app/src/main/java/com/orange/ods/app/ui/guidelines/spacing/GuidelineSpacingScreen.kt
>                  secondaryText = stringResource(id = R.string.guideline_spacing_dp, dp.value.toInt()) + "\n",
Do we need to display kotlin code for each item to use the spacing? `OdsTheme.spacings.small` for example.

2024-05-23 14:48 UTC, florentmaitre commented on theme-contract/src/main/java/com/orange/ods/theme/spacing/OdsSpacings.kt
> +interface OdsSpacingsCatalog<T> : OdsThemeConfigurationItem.Catalog<T> {
Yes, we also have an `OdsSpacingsCatalog` of `OdsToken<OdsSpacing>>`.

2024-05-24 14:56 UTC, paulinea approved these changes

2024-05-24 14:56 UTC, merged